learner:
  alg: ppo
  env: PongNoFrameskip-v4
  num_steps: 10000000
  data_port: 5000
  param_port: 5001
  model: accnn
  pool_size: 1000
  training_freq: 1
  batch_size: 1000

agent:
  gamma: 0.97
  lam: 0.98
  pi_lr: 0.0003
  vf_lr: 0.001
  clip_range: 0.2
  ent_coef: 0.01
  epochs: 10
  target_kl: 0.01
  model:
    model_id: policy_model
